name: FD-j3s - clang-r547379 tester debug

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/re-noroi/kernel_sm8250'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        required: true
        default: 'tester-j3sbattery'
      CODENAME:
        description: 'Phone Codename'
        default: 'alioth'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/re-noroi/anykernel3-test'
        required: false
      ANYKERNEL_BRANCH:
        description: 'AnyKernel Branch (defaults to codename)'
        default: 'main'
        required: false
      UPLOAD_TO_RELEASE:
        description: 'Upload to release'
        type: boolean
        default: false

jobs:
  build_original:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
          mkdir clang
          unzstd -d clang.tar.zst
          tar -xf clang.tar -C clang

      - name: Checkout Kernel
        run: git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree

      - name: Apply Patches
        run: |
          cd kernel_tree
          bash nextpatch.sh

      - name: Apply Modifications
        run: |
          cd kernel_tree
          sed -i -e 's/# CONFIG_LTO_CLANG_THIN is not set/CONFIG_LTO_CLANG_THIN=y/' arch/arm64/configs/vendor/alioth_defconfig
          sed -i -e 's/CONFIG_LTO_CLANG_FULL=y/# CONFIG_LTO_CLANG_FULL is not set/' arch/arm64/configs/vendor/alioth_defconfig
      
      - name: Build Kernel - Original
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="renoroi"
          export KBUILD_BUILD_HOST="dreamstate"
          cd kernel_tree
          make O=out vendor/alioth_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          cp out/arch/arm64/boot/Image.gz ../Image-original.gz
          cp out/arch/arm64/boot/dtb.img ../dtb-original.img || true
          cp out/arch/arm64/boot/dtbo.img ../dtbo-original.img || true

      - name: Upload Original Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: original-build
          path: |
            Image-original.gz
            dtb-original.img
            dtbo-original.img

  build_modified:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
          mkdir clang
          unzstd -d clang.tar.zst
          tar -xf clang.tar -C clang

      - name: Checkout Kernel
        run: git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree

      - name: Apply Patches
        run: |
          cd kernel_tree
          bash nextpatch.sh

      - name: Apply Modifications
        run: |
          cd kernel_tree
          sed -i -e 's/# CONFIG_LTO_CLANG_THIN is not set/CONFIG_LTO_CLANG_THIN=y/' arch/arm64/configs/vendor/alioth_defconfig
          sed -i -e 's/CONFIG_LTO_CLANG_FULL=y/# CONFIG_LTO_CLANG_FULL is not set/' arch/arm64/configs/vendor/alioth_defconfig
          sed -i -e '/<2553600>,/c\<2553600>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2649600>,/c\//<2649600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2745600>,/c\//<2745600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2841600>,/c\//<2841600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<3187200>;/c\//<3187200>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-width-dimension = <70>;/qcom,mdss-pan-physical-width-dimension = <700>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-height-dimension = <155>;/qcom,mdss-pan-physical-height-dimension = <1540>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi

      - name: Build Kernel - Modified
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="renoroi"
          export KBUILD_BUILD_HOST="dreamstate"
          cd kernel_tree
          make O=out vendor/alioth_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          cp out/arch/arm64/boot/Image.gz ../Image-modified.gz
          cp out/arch/arm64/boot/dtb.img ../dtb-modified.img || true
          cp out/arch/arm64/boot/dtbo.img ../dtbo-modified.img || true

      - name: Upload Modified Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modified-build
          path: |
            Image-modified.gz
            dtb-modified.img
            dtbo-modified.img

  package_anykernel:
    needs: [build_original, build_modified]
    runs-on: ubuntu-latest
    steps:
      - name: Download Original Kernel
        uses: actions/download-artifact@v4
        with:
          name: original-build
          path: .

      - name: Download Modified Kernel
        uses: actions/download-artifact@v4
        with:
          name: modified-build
          path: .

      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b ${{ github.event.inputs.ANYKERNEL_BRANCH || github.event.inputs.CODENAME }} AnyKernel3

      - name: Add Kernel Images to AnyKernel3
        run: |
          cp Image-original.gz AnyKernel3/Image.gz
          if [ -e "dtb-original.img" ]; then
          mv -f dtb-original.img dtb1
          cp -f dtb1 AnyKernel3/alioth-normal-dtb
          fi
          if [ -e "dtb-modified.img" ]; then
          mv -f dtb-modified.img dtb2
          cp -f dtb2 AnyKernel3/alioth-effcpu-dtb
          fi
          cp dtbo-original.img AnyKernel3/alioth-aosp-dtbo.img || true
          cp dtbo-modified.img AnyKernel3/alioth-miui-dtbo.img || true
          name=FakeDreamer-j3s-test-${{ github.event.inputs.CODENAME }}-${{ github.run_id }}.zip
          cd AnyKernel3
          zip -q -r $name *
          mv $name ../

      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: FakeDreamer-j3s-test-${{ github.event.inputs.CODENAME }}-${{ github.run_id }}
          path: FakeDreamer-j3s-test-${{ github.event.inputs.CODENAME }}-${{ github.run_id }}.zip
